language: node_js
node_js:
- node
script:
- yarn install
- yarn run build
deploy:
  provider: firebase
  token:
    secure: SK0Ekn5194UzzSItYbGZ6cACM0AroV1oUiyGv8U0ZU24+FgoHHWkl5iqQWjG3/W641SpXPh2NpAXDM8JhwQg1PHz3suFtDSU+cpV8Wtg5OOPYOS9yyufE69i3R6jIIgvFUwfBWTf9MsL7FDfxsi1HBgCY29kGcD/cRjgLc89cXlw5TdCbL+bDLNojCKys7ffaItc2dQ8JdHgjQg53ooFomoOnlhb3LeS68WZArCm6J0KXY6n4VgoH5gtqAs9VowfMXM6ylooDo64Orx8Ad7d0oBEwLlAuzkgtKOoJpMbPqc0VpVVjclE9rBVTipe+jHr4TLsTYJIExzg4flDg3/4hSIx8UTMNCo/qBCfsU8zgwgpfGQZU+bEPR2aJbXcWk/CelIm5ldGIIphZHyu3l66xjSQiHJZ9i01s8d3oycVptHkgc82lkVhJoCQSxrmDQIHCQCWuaCBeV/2JZzKSQx5x/yHP2tU0K+lECpVFjTmN7vpgYeyVE6zxqzbyQrlBAb91sb19okQUVhLw6spbcQskoEPZdTLXUWzi6/HEhbVK/K6NOsQi81CUOj/k1pKj0FE3Bw1LaksuUphoRQ9/hpZ/DkIMCUTRkf8XCIH74ULtp5JaqlIYcNp4rKBzb5be8B4afNPVzeX/5863QV0hAXc+FXxjXh4rRWTg+BCUsbEiMI=
  project: securethebox-client
  message: travis deployment to firebase hosting