language: node_js
node_js:
- node
script:
- yarn install
- yarn run build
deploy:
  provider: firebase
  project: thebox-client
  message: travis deployment to firebase hosting
  token:
    secure: "U2QPcVNrfUfXcX9/vT8GLqmj36ETF8ok1WKV/+cGg86s+KF2jg+vuCq+9TPGsyBCj16Yj4CdKibPp8RTuDqwKqTx5juo8/DxtMjM5f9v3yI/BtzDhee10YYShs0ooosnp2OsHMBU2xAC1Bsx9EZcKe3N1Gd8BEWiUxsKlGMrOya71yei/PG+Fov9fwxHPoRyARw5ZnH8Hnj2CCNeMXgPkgNlBVeRGuPJMc+4sa3+7wo/Jsbev/USSld4A6hF93o6XW3Z8Sb17UNXUvz5LcXdSaVkcBji4WaVByjAIxVgMhqVUxReZRc5nH4tVbEuPOzwGQVkcRGysg5L8xPC35yBi5x2bJPY5mQBn+0od4MvfaazS0K3D0PCEEIM75JaeVGVjmYotKdcRFzIuuZMWiz/Ehv8Z+qvIXlBdWDyShCf5dxVV7hiLTJoZNFTRfKeiBIK/hrb2P1U6pdg24r3SsyHdffluOyxLnYyZIAtLYE5oX/nQlGeCb9uoqo85vBGFbwADlwaf4zOxHzKGCBgl6jX3vmjDItBRn4wUkmUije2WdotWwjmLr41rS3e7UgbR0wOHzI13D/RY9YIZgOj3JCSqJgZmhk5c7ZYB/OpeddxOHgh03lli50wcif5pIo1ezCG5j6tY0AOSDDHn8JcoATLC6GNDQjCub2ZiMVLVULExrY="
env:
  global:
  - secure: "U2QPcVNrfUfXcX9/vT8GLqmj36ETF8ok1WKV/+cGg86s+KF2jg+vuCq+9TPGsyBCj16Yj4CdKibPp8RTuDqwKqTx5juo8/DxtMjM5f9v3yI/BtzDhee10YYShs0ooosnp2OsHMBU2xAC1Bsx9EZcKe3N1Gd8BEWiUxsKlGMrOya71yei/PG+Fov9fwxHPoRyARw5ZnH8Hnj2CCNeMXgPkgNlBVeRGuPJMc+4sa3+7wo/Jsbev/USSld4A6hF93o6XW3Z8Sb17UNXUvz5LcXdSaVkcBji4WaVByjAIxVgMhqVUxReZRc5nH4tVbEuPOzwGQVkcRGysg5L8xPC35yBi5x2bJPY5mQBn+0od4MvfaazS0K3D0PCEEIM75JaeVGVjmYotKdcRFzIuuZMWiz/Ehv8Z+qvIXlBdWDyShCf5dxVV7hiLTJoZNFTRfKeiBIK/hrb2P1U6pdg24r3SsyHdffluOyxLnYyZIAtLYE5oX/nQlGeCb9uoqo85vBGFbwADlwaf4zOxHzKGCBgl6jX3vmjDItBRn4wUkmUije2WdotWwjmLr41rS3e7UgbR0wOHzI13D/RY9YIZgOj3JCSqJgZmhk5c7ZYB/OpeddxOHgh03lli50wcif5pIo1ezCG5j6tY0AOSDDHn8JcoATLC6GNDQjCub2ZiMVLVULExrY="
